In [1]:
import numpy as np

In [5]:
ar = np.array([[0,1,3,0],
                [-2,3,0,4],
                [0,0,6,1],
                [0,0,1,6]])

In [6]:
np.linalg.eig(ar)

(array([1., 2., 7., 5.]),
 array([[-0.70710678, -0.4472136 ,  0.31747032, -0.06428243],
        [-0.70710678, -0.89442719,  0.43652168,  0.83567165],
        [ 0.        ,  0.        ,  0.59525684, -0.38569461],
        [ 0.        ,  0.        ,  0.59525684,  0.38569461]]))

In [ ]:
dim = int(input('Enter dimension of the array: '))
ar2 = []

for i in range(dim):
    temp = []
    for j in range(dim):
        temp.append(int(input(f'row {i} column {j}: ')))
    ar2.append(temp)

ar2 = np.array(ar2)
eigen_values, eigen_vectors = np.linalg.eig(ar2)

In [7]:
print(f'Eigen Values: {eigen_values}')
print(f'Eigen Vectors: {eigen_vectors}')

NameError: name 'eigen_values' is not defined

In [7]:
for i in range(dim):
    t1 = ar2 @ eigen_vectors[:,i]
    t2 = eigen_values[i] * eigen_vectors[:,i]
    print(f'With Matrix: {t1}\nWith Eigen Value: {t2}')

With Matrix: [-4.89906948 -5.20829309 -8.12476358]
With Eigen Value: [-4.89906948 -5.20829309 -8.12476358]
With Matrix: [ 1.99867541 -1.55325937 -0.63922645]
With Eigen Value: [ 1.99867541 -1.55325937 -0.63922645]
With Matrix: [-0.06644438  0.17049457 -0.10773258]
With Eigen Value: [-0.06644438  0.17049457 -0.10773258]


# Singular value decomposition

In [18]:
A = np.array([[3,2,2],[2,3,-2]])

eig1, U = np.linalg.eig(A @ A.T)
eig2, V = np.linalg.eig(A.T @ A)

print(f'for AAt, eigen values = {eig1}\neigen vectors = {U}')
print(f'for AtA, eigen values = {eig2}\neigen vectors = {V}')


for AAt, eigen values = [25.  9.]
eigen vectors = [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
for AtA, eigen values = [2.5000000e+01 5.0324328e-15 9.0000000e+00]
eigen vectors = [[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]


In [19]:
A @ V[:,2]

array([ 2.12132034, -2.12132034])

In [4]:
9 * V[:,2]

array([ 2.12132034, -2.12132034,  8.48528137])

In [5]:
np.linalg.eig(A @ A.T)

(array([25.,  9.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [6]:
V = np.array([V[:, 0], V[:,2], V[:,1]])
V = V.T

In [7]:
print(f'U shape: {U.shape}\nV shape: {V.shape}')

U shape: (2, 2)
V shape: (3, 3)


In [8]:
lambda_ = np.array([[np.sqrt(eig1[0]),0,0], [0,np.sqrt(eig1[1]),0]])
print(f'U={U}\nlambda={lambda_}\nV={V}')

U=[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
lambda=[[5. 0. 0.]
 [0. 3. 0.]]
V=[[-7.07106781e-01  2.35702260e-01 -6.66666667e-01]
 [-7.07106781e-01 -2.35702260e-01  6.66666667e-01]
 [-4.55680392e-17  9.42809042e-01  3.33333333e-01]]


In [10]:
np.linalg.svd(A)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [12]:
U@lambda_@V.T

array([[-3., -2., -2.],
       [-2., -3.,  2.]])

In [13]:
def svd(A, tol=1e-9):
    """
    Compute the Singular Value Decomposition of matrix A.

    Args:
    A (numpy.ndarray): The input matrix.
    tol (float): Tolerance for singular value truncation.

    Returns:
    U (numpy.ndarray): Left singular vectors.
    S (numpy.ndarray): Singular values.
    VT (numpy.ndarray): Right singular vectors (transposed).
    """
    # Step 1: Compute A^T * A and A * A^T
    ATA = np.dot(A.T, A)
    AAT = np.dot(A, A.T)
    
    # Step 2: Compute the eigenvalues and eigenvectors of A^T * A
    eigenvalues, U = np.linalg.eig(ATA)
    
    # Sort eigenvalues and corresponding eigenvectors in descending order
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    U = U[:, sorted_indices]
    
    # Step 3: Compute the singular values and V matrix
    S = np.sqrt(np.abs(eigenvalues))
    V = np.dot(np.linalg.inv(np.diag(S)), np.dot(U.T, A))
    
    # Truncate small singular values and corresponding columns of U and V
    rank = np.sum(S > tol)
    U = U[:, :rank]
    S = S[:rank]
    V = V[:rank, :]
    
    return U, S, V.T

# Example usage:
# A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# U, S, VT = svd(A)
# print("U:\n", U)
# print("S:\n", S)
# print("VT:\n", VT)


In [14]:
svd(A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)