In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

import glob

## Image Pre-Processing

In [27]:
# Open the image using PIL
image_pil = Image.open('./Caltech_WebFaces/pic00001.jpg')  # Replace 'image.jpg' with the path to your image file
image_pil = image_pil.convert('L')
# Convert the PIL image to a NumPy array
image = np.array(image_pil)

# 'image' is now a NumPy array containing the image data
print(np.array([image.T.ravel()]).T)


[[255]
 [255]
 [255]
 ...
 [255]
 [255]
 [255]]


In [20]:
# Create a 2D NumPy matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Use numpy.ravel() to stack the columns into a column vector
column_vector = np.array([matrix.T.ravel()])

# Print the resulting column vector
print(np.column_stack([column_vector.T, column_vector.T]))


[[1 1]
 [4 4]
 [7 7]
 [2 2]
 [5 5]
 [8 8]
 [3 3]
 [6 6]
 [9 9]]


In [13]:
filez = glob.glob('./Caltech_WebFaces/set_1/*.jpg')  
filez = [file.replace('\\', '/') for file in filez]

In [12]:
for file in filez:
    width, height = 50, 50
    white_image = Image.new('RGB', (width, height), color='white')
    image_to_paste = Image.open(file)  # Replace with the path to your image

    original_width, original_height = image_to_paste.size

    # Set the maximum dimension (either width or height) to 500 pixels
    max_dimension = 200

    # Calculate the new dimensions while preserving the aspect ratio
    if original_width > original_height:
        new_width = max_dimension
        new_height = int(max_dimension * (original_height / original_width))
    else:
        new_height = max_dimension
        new_width = int(max_dimension * (original_width / original_height))

    # Resize the image
    resized_image = image_to_paste.resize((new_width, new_height), Image.Resampling.LANCZOS)

    # Calculate the position to paste the image in the center
    x_position = (white_image.width - resized_image.width) // 2
    y_position = (white_image.height - resized_image.height) // 2

    # Paste the image onto the white image
    white_image.paste(resized_image, (x_position, y_position))

    # Save the combined image or display it
    white_image.save(file)
    # Close the images
    white_image.close()
    image_to_paste.close()

# Loading Images

In [6]:
image_list = []

max_x = 0
max_y = 0

for file in filez:
    # print(f'Opening: {file}')
    image = Image.open(file)
    image = image.convert('L')
    image_vector = np.array(image)
    image_list.append(np.array([image_vector.T.ravel()]).T)

In [10]:
final_matrix = np.column_stack(image_list)

In [12]:
final_matrix.shape

(40000, 7092)

In [56]:
output = np.linalg.svd(final_matrix)

In [58]:
output[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
img = Image.open('./pic00005.jpg')
resized_image = img.resize((50, 50), Image.Resampling.LANCZOS)

In [15]:
for file in filez:
    width, height = 64, 64
    white_image = Image.new('RGB', (width, height), color='white')
    image_to_paste = Image.open(file)  # Replace with the path to your image

    original_width, original_height = image_to_paste.size

    # Set the maximum dimension (either width or height) to 500 pixels
    max_dimension = 64

    # Calculate the new dimensions while preserving the aspect ratio
    if original_width > original_height:
        new_width = max_dimension
        new_height = int(max_dimension * (original_height / original_width))
    else:
        new_height = max_dimension
        new_width = int(max_dimension * (original_width / original_height))

    # Resize the image
    resized_image = image_to_paste.resize((new_width, new_height), Image.Resampling.LANCZOS)
    # Calculate the position to paste the image in the center
    x_position = (white_image.width - resized_image.width) // 2
    y_position = (white_image.height - resized_image.height) // 2

    # Paste the image onto the white image
    white_image.paste(resized_image, (x_position, y_position))

    white_image.save(file)
    white_image.close()
    image_to_paste.close()